apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234

    jwt:
      expires-in: 86400
      mobile-expires-in: 31536000
      table-expires-in: 31536000
      secret-key: AADfaskllewjihjkhughjgygjfhf32dsfasdTG764Gdslkj298GsWg86G
