apiVersion: v1
kind: Service
metadata:
  name: k8s-user-service-nodeport
spec:
  type: NodePort # default는 ClusterIp
  selector:
    app: k8s-user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
