apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  application-dev.yml: |
    server:
      port: 8080

    spring:
      datasource:
        url: jdbc:mysql://k8s-user-service-jdbc:3306?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          connection-test-query: SELECT 1
          validation-timeout: 5000

      jpa:
        hibernate:
          ddl-auto: update
          generate-ddl: true
          show-sql: true
        open-in-view: false
        properties:
          hibernate:
            format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
